### ISSUE TITLE
Akeeba extract wizard fails because of false file name

### ISSUE THREAD

**Issue by bege10** [akeeba/nativexplatform#13]
Because of a filename with ":" the extract wizard fails. Please, make the wizard ignore such files and continue extracting.
Thank you very much.

**Comment by nikosdion** [comment]
There is the “Ignore most errors” checkbox which does exactly that: if the file name is invalid, it will skip the file. We put it there for extracting files on Windows which has stricter file name validation rules than Linux, macOS and other UNIX-style Operating Systems.

**Comment by bege10** [comment]
I checked "Ignore file write errors" and the extract wizard terminates with the error message, that the path pattern is not supported. In the Windows version there is no box “Ignore most errors”.

**Comment by davidpenwell** [comment]
I am having the same issue, please advise. I have checked the "Ignore file write errors" and I am still getting the same error. The "Test without extracting" completes successfully, but a real extraction stops. I am unable to get the file that I need from the backup.

**Comment by nikosdion** [comment]
Upgrade to version 4.0.5 and retry.

**Comment by bege10** [comment]
I upgraded to version 4.0.5.29360. The error remains.
Additionally, the Wizard extracts to the folder of the backup file, it does not add a folder with the name of the backup file. This was the case in the previous version already.

**Comment by nikosdion** [comment]
Cannot reproduce on Windows 10.

I have no idea how you ended up without the additional folder, either. This is something added by the interface, not the extraction engine. This part has not been touched since 4.0.1.

Whatever the problem you have is it's not something related to the software. If you still have problems just use Akeeba Kickstart on a local web server. If you have problems with that just reformat your computer and don't install shitty antivirus / anti-malware which block file writes.

I am now going to lock this ticket since this issue is REALLY FIXED and impossible to reproduce on non-broken Windows 10 installations.
