### ISSUE TITLE
extracted files 0 bytes(empty)

### ISSUE THREAD

**Issue by just4t** [akeeba/nativexplatform#3]
- *.jps file created with 'Akeeba Backup Professional 5.3.1 (2017-03-16)'
- Extracted with 'AkeebaPortableTools / Akeeba eXtract Wizard 4.0.1.29270' **windows** version.
>> Result: All extracted files are 0 bytes (empty):

![jps-extract-issue-17-03-24-05-39-20](https://cloud.githubusercontent.com/assets/13877636/24333877/622d37ba-1260-11e7-8ebf-3db2db01999b.png)

**Comment by nikosdion** [comment]
Thank you for your report and sorry for taking so long to respond. It's been a very busy week, mostly with non-coding emergencies I had to deal with.

The problem is indeed caused by a bug. Can you please try installing the latest [dev release](https://dl.dropboxusercontent.com/u/5168399/GitHub%20-%20Dev%20Releases%20for%20issues/AkeebaPortableToolsSetup.exe) and confirm it?

For anyone interested, the problem was in the way streams are handled by the JPS extraction engine. The on-disk data is compressed and encrypted. So first we decrypt them in a stream, then that stream is sent through an extraction stream and the resulting stream is copied to a memory stream. The last operation is the only way to be sure about the real size of the decrypted data (since the extraction stream doesn't have such a property) which will then be compared to the stored value to make sure the extracted data is not corrupt. The memory stream is then copied to the output file stream.

The keen observer may have noticed a problem here: we don't rewind the memory stream. AFter writing to it the stream pointer is at the end of the stream. Therefore copying from it to the file stream always results in 0 bytes being copied. Hence the 0-byte size of the extracted files. The simple solution was to, of course, rewind the memory stream before writing to file.

**Comment by just4t** [comment]
Thanks! Confirmed 'Akeeba eXtract Wizard 4.0.2.14969' ,windows version' works as needed, both scenarios:
- Extracted OLD 'Akeeba Backup Professional 5.2.5 (2016-12-12)'  *.jps file, correctly.
- Extracted 'Akeeba Backup Professional 5.3.1 (2017-03-16)' *.jps file, correctly, too.
Hope this helps.
best.

**Comment by nikosdion** [comment]
Awesome! Thanks a lot for your report and your feedback :)

**Comment by just4t** [comment]
Have you plans to make the told dev. 4.0.2.14969 the one officially available soon?
- Just because end customers are still trying to extract their *.jps by using the wrong 401 and then fails and then they claim about again and again ... It's getting annoying to tell to each one where the hidden link, for the version that works, is currently located!

**Comment by nikosdion** [comment]
Most likely after Easter, i.e. around April 18th. There's a lot of other stuff we need to get done before that date. Sorry :(

**Comment by just4t** [comment]
Thanks for feedback! ... 2nd. half of April more than enough. Thanks in advance!
