### ISSUE TITLE
4.0.3: Windows10 install error warning ... 3

### ISSUE THREAD

**Issue by just4t** [akeeba/nativexplatform#8]
So the Windows10 warning should not popup if the 'App. Publisher' should be added in.
Hope this helps (again)

**Comment by nikosdion** [comment]
You are completely ignorant. It's not about filling a field. It's about code signing. Code signing requires a certificate which costs 350€ PER YEAR (or "only" 90 if you get a lousy one that may still pop a warning). 

In case you missed it, this software here is free of charge. I make exactly 0€ per year out of it, it makes no impact to our bottom line and I'm putting dozens of hours (over 100 this year). So I'm already losing money. 

Would you like me to make this a paid software? Or would to like to sponsor me with 350€ per year? If so, yup, I can sign the code. Otherwise just read the dialog and accept the installation. Demanding that I spend a month's rent, on top of my time, on this FOSS software just because you are too lazy to click a button is unacceptable. Put your money where your mouth is or shut it. Thank you for not opening another issue AGAIN.
